#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"
if [[ "$(uname -s)" != Darwin ]]; then
  echo "Build this project on a Mac with Apple's Command Line Tools installed."
  exit 1
fi
if ! xcrun --find clang >/dev/null 2>&1; then
  echo "Install Apple's compiler with: xcode-select --install"
  echo "When installation finishes, run this script again."
  exit 1
fi
sdk_path="$(xcrun --sdk macosx --show-sdk-path)"
output_dir="$PWD/build"
saver_dir="$output_dir/Atelier Clock.saver"
app_dir="$output_dir/Atelier Clock.app"
mkdir -p "$saver_dir/Contents/MacOS" "$saver_dir/Contents/Resources" "$app_dir/Contents/MacOS" "$app_dir/Contents/Resources"
cp Resources/Saver-Info.plist "$saver_dir/Contents/Info.plist"
cp Resources/App-Info.plist "$app_dir/Contents/Info.plist"
# Screen Saver picker artwork (standard and Retina), separate from the live preview.
cp Resources/thumbnail.png Resources/thumbnail@2x.png "$saver_dir/Contents/Resources/"
cp Resources/AtelierClock.icns "$saver_dir/Contents/Resources/"
cp Resources/AtelierClock.icns "$app_dir/Contents/Resources/"
# Wood is generated by the renderer. Remove obsolete generated assets when
# rebuilding an older checkout so photographs cannot linger in signed products.
rm -rf "$output_dir/Wood" "$saver_dir/Contents/Resources/Wood" "$app_dir/Contents/Resources/Wood"
# Inject the platform/SDK build metadata that Xcode normally adds. macOS 14+
# (including macOS 26) requires these keys for its Screen Saver picker to render
# a live preview and expose the Options button; xcrun clang does not add them.
sdk_version="$(xcrun --sdk macosx --show-sdk-version)"
sdk_build="$(xcrun --sdk macosx --show-sdk-build-version)"
os_build="$(sw_vers -buildVersion)"
pb=/usr/libexec/PlistBuddy
add_build_metadata() {
  local plist="$1"
  "$pb" -c "Delete :CFBundleSupportedPlatforms" "$plist" 2>/dev/null || true
  "$pb" -c "Add :CFBundleSupportedPlatforms array" "$plist"
  "$pb" -c "Add :CFBundleSupportedPlatforms:0 string MacOSX" "$plist"
  for entry in \
    "DTPlatformName=macosx" \
    "DTPlatformVersion=$sdk_version" \
    "DTPlatformBuild=$sdk_build" \
    "DTSDKName=macosx$sdk_version" \
    "DTSDKBuild=$sdk_build" \
    "DTCompiler=com.apple.compilers.llvm.clang.1_0" \
    "BuildMachineOSBuild=$os_build"; do
    key="${entry%%=*}"; value="${entry#*=}"
    "$pb" -c "Delete :$key" "$plist" 2>/dev/null || true
    "$pb" -c "Add :$key string $value" "$plist"
  done
}
add_build_metadata "$saver_dir/Contents/Info.plist"
add_build_metadata "$app_dir/Contents/Info.plist"
common_flags=(-fobjc-arc -O2 -Wall -Wextra -Wno-unused-parameter -isysroot "$sdk_path" -mmacosx-version-min=13.0 -arch arm64 -arch x86_64 -framework Cocoa -framework ScreenSaver)
echo "Building universal screensaver (Apple Silicon + Intel)…"
xcrun clang "${common_flags[@]}" -bundle Sources/AtelierClockView.m -o "$saver_dir/Contents/MacOS/AtelierClock"
echo "Building desktop clock…"
xcrun clang "${common_flags[@]}" Sources/AtelierClockView.m Sources/main.m -o "$app_dir/Contents/MacOS/AtelierClock"
plutil -lint "$saver_dir/Contents/Info.plist" "$app_dir/Contents/Info.plist"
codesign --force --sign - "$saver_dir"
codesign --force --sign - "$app_dir"
codesign --verify --strict "$saver_dir"
codesign --verify --strict "$app_dir"
echo "Built successfully:"
echo "$saver_dir"
echo "$app_dir"
